### PR TITLE
feat(inspect): inspect common holdings

### PR DESCRIPTION
**Pull request by bitbeckers**
Adds inspect page

## Release Notes

- **New Features**
  - Introduced a `CommunityPage` for managing staking activities with the `$COMMONS` token.
  - Added an `InsightPage` to fetch and display account insights, including balances and staked NFTs.
  - New `Skeleton` component for improved loading state presentation.

- **Enhancements**
  - Updated the header to include a new "Inspect" menu item.
  - Expanded blockchain support to include `mainnet` in the configuration.

- **Dependencies**
  - Added new libraries: `chart.js`, `graphql`, `graphql-request`, and `react-chartjs-2` for enhanced data visualization and interactions.

- **Configuration**
  - Changed TypeScript module resolution strategy to `Bundler`.

### CODE REVIEW

**Comment by daviddao** [comment]
lgtm! suggestion to fix the negative token amount from the 0x000... account

Screenshot 2024-10-23 at 00 51 57

**Comment by tnkshuuhei** [comment]
Screenshot 2024-10-23 at 0 52 12

@bitbeckers can you apply this change?

```diff
tsconfig.json
-  "moduleResolution": "Node",
+  "moduleResolution": "Bundler",
```

**Comment by tnkshuuhei** [comment]
Screenshot 2024-10-23 at 1 41 51

app/inspact/pages.tsx

```diff
-    const [accounts, setAccounts] = useState<Account[]>([]);
-    const [isLoading, setIsLoading] = useState(true);

-   useEffect(() => {
-        const fetchData = async () => {
-            try {
-                const data = await request('https://indexer.bigdevenergy.link/92f8c3e/v1/graphql/', QUERY_DOCUMENT);
-                setAccounts(data.Account);
-            } catch (error) {
-                console.error("Error fetching data:", error);
-            } finally {
-                setIsLoading(false);
-            }
-        };
-        fetchData();
-    }, []);
```

this change makes sense to you...?
```typescript

import { useQuery } from "@tanstack/react-query";

  const {
    data: accounts,
    isLoading,
    error,
  } = useQuery<Account[]>({
    queryKey: ["account"],
    async queryFn() {
      try {
        return await request(
          "https://indexer.bigdevenergy.link/92f8c3e/v1/graphql/",
          QUERY_DOCUMENT
        ).then((data: any) => data.Account);
      } catch (error) {
        console.error(error);
        throw new Error("Error fetching accounts");
      }
    },
  });
```

**Comment by tnkshuuhei** [comment]
GJ @bitbeckers @daviddao

**Pull request merged**
